### ISSUE TITLE
Java in-process agent version to be upgraded

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/Azure-Spring-Apps#10]
**Is your feature request related to a problem? Please describe.**
Java in-process agent version deployed is 3.3.1

**Describe the solution you'd like**
Java in-process agent version should be updated to latest 3.4.4

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

@msftgits @xscript

**Comment by domainname** [comment]
Since App Insights agent has been upgraded in Jan 2023, I'm closing this issue now.
