### ISSUE TITLE
RFE: provide API & CLI to to know if a Deployment is a STAGING or a PRODUCTION one

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/Azure-Spring-Apps#17]
Today running az spring app set-deployment -d $DEPLOYMENT_NAME will fail with error message when this $DEPLOYMENT_NAME is already set to Production.
In a Pipeline / GH Workflow, there is no way to guess if that $DEPLOYMENT_NAME is a STAGING or a PRODUCTION one

```sh
az spring app set-deployment -d $DEPLOYMENT_NAME -n ${{ env.CUSTOMERS_SERVICE }} --service ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }}
```

**Describe the solution you'd like**
Please provide [REST API](https://learn.microsoft.com/en-us/rest/api/azurespringapps/deployments/get?tabs=HTTP#deploymentresourceproperties) + CLI + Bicep to know if a Deployment is a STAGING or a PRODUCTION one.

**Describe alternatives you've considered**
None, the only option is to look from the Azure portal, impossible from a Pipeline / GH Workflow,

**Additional context**
N/A

**Comment by ezYakaEagle442** [comment]
update: in CLI az spring app deployment list 
the [].properties.active = true mean it is a Production one but it would help to have a clear API about this.

**Comment by yuwzho** [comment]
@ezYakaEagle442 Can you explain more why you need an API to get this info?

For CLI wise, you can run this command to get the production deployment name using Query parameter

This is used for getting production deployment
```
az spring app deployment list --app ${{ env.CUSTOMERS_SERVICE }} ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} --query "[?properties.active].name"
```


This is used for getting stagingdeployment
```
az spring app deployment list --app ${{ env.CUSTOMERS_SERVICE }} ${{ env.AZURE_SPRING_APPS_SERVICE }} -g ${{ env.RG_APP }} --query "[?properties.active==`false`].name"
```

**Comment by allxiao** [comment]
An alternative way to resolve this is to make the `set-deployment` call idempotent:
* if the deployment is staging, set it to production
* if the deployment is production already, just skip and return succeeded rather than raise an error

It's common to retry such commands in an environment with pool network condition. The current behavior is a blocker to such idempotent retry pattern.

**Comment by yuwzho** [comment]
Steve is using this command to find which deployment to be deployed. He  can now find the target one with provided command. Let me close this  issue. Please reach out to me if any.
