### ISSUE TITLE
Enterprise Tier from Azure Market Place: wizard configure Basic Tier

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/Azure-Spring-Apps#19]
Go to the Azure Market Place, select Azure Spring Apps Enterprise  , once you land on the Azure Portal, the service is configured with Basic Tier on the screen whereas it should be Enterprise Tier

**Expected behavior**
In the Azure Portal , Enterprise Tier should be selected by default in this scenario

**Comment by seanli1988** [comment]
basic tier is the default due to low price entry. closing this issue as it's by design.
