### ISSUE TITLE
Add Support for Azure Policy 

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/Azure-Spring-Apps#23]
**Is your feature request related to a problem? Please describe.**
As an enterprise customer, having support for AKS like Policy initiatives will help ensure security and compliance.

For instance :

- Deny App exposition with public endpoint
- Allow container deployment using images from allowed registries (ex: Trust ACR but Deny Dockerhub)
- etc.

**Describe the solution you'd like**
Support [Azure Policy](https://learn.microsoft.com/en-us/azure/aks/use-azure-policy) which extends Gate Keeper V3 / OPA, we already provide more than ~42 [Built-in Policies](https://learn.microsoft.com/en-us/azure/aks/policy-reference#policy-definitions)

**Describe alternatives you've considered**
None

**Additional context**
See [https://learn.microsoft.com/en-us/azure/spring-apps/security-controls-policy](https://learn.microsoft.com/en-us/azure/spring-apps/security-controls-policy)

**Comment by seanli1988** [comment]
This is already possible with Azure policies. We will document how to achieve this in ASA documentation or offer default policies

**Comment by bowen5** [comment]
Assign to @Descatles who is already looking into this.

**Comment by Descatles** [comment]
We have updated our alias manifest to the api version 2022-11-01-preivew, all properties in that version could be used in Azure policy now.
