### ISSUE TITLE
Private-Endpoints support 

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/Azure-Spring-Apps#25]
**Is your feature request related to a problem? Please describe.**
To secure access to the ASA control plane, we should support a private, single tenant service with Private-Endpoints.

**Describe the solution you'd like**
Private-Endpoints support like it is supported in AKS with private clusters.
See [https://learn.microsoft.com/en-us/azure/aks/private-clusters](https://learn.microsoft.com/en-us/azure/aks/private-clusters)

**Describe alternatives you've considered**
[https://github.com/Azure/Azure-Spring-Apps/issues/24](https://github.com/Azure/Azure-Spring-Apps/issues/24)

**Additional context**
Highly regulated industries have a golden rule n°1 for instance which states : Public IP on Control Plane is DENIED.

**Comment by seanli1988** [comment]
this is a showstopper for many customers to move forward

**Comment by ezYakaEagle442** [comment]
- [https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/azure-spring-apps-security-baseline#ns-2-secure-cloud-services-with-network-controls](https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/azure-spring-apps-security-baseline#ns-2-secure-cloud-services-with-network-controls)
- [https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/spring-cloud-security-baseline?toc=%2Fazure%2Fspring-apps%2Ftoc.json&bc=%2Fazure%2Fspring-apps%2Fbreadcrumb%2Ftoc.json](https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/spring-cloud-security-baseline?toc=%2Fazure%2Fspring-apps%2Ftoc.json&bc=%2Fazure%2Fspring-apps%2Fbreadcrumb%2Ftoc.json)

**Comment by allxiao** [comment]
The concept was mapped incorrectly from AKS to Azure Spring Apps (ASA).

In AKS,
1. You provision an AKS cluster through the **public** ARM endpoints
2. You work with the API server (either public or private) to operate on the Kubernetes resources. This is now purely on Kubernetes world and outside of the control of ARM, unless you use the RBAC from Azure. Generally we call this data plane and data plane API.

The private endpoints in AKS are actually endpoints for the data plane. You do not have a private ARM endpoint so all AKS related (not Kubernetes related) operations are performed against the **public** ARM endpoints, regardless of whether the underlying API server is public or private.

In ASA, we do not have such kind of data plane concept. All the resource manipulation is done through the ARM endpoint. You call ARM APIs to CRUD services, apps, deployments, etc. The only data plane API provided is the APIs exposed by the managed components, such as Config Server, Eureka, and enterprise tier components. Currently, the endpoints for these components are private if you use VNET injection feature. 

* [Deploy Azure Spring Apps in a virtual network | Microsoft Learn](https://learn.microsoft.com/en-us/azure/spring-apps/how-to-deploy-in-azure-virtual-network?tabs=azure-portal)

**Comment by ezYakaEagle442** [comment]
see [https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/public-and-private-aks-clusters-demystified/ba-p/3716838](https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/public-and-private-aks-clusters-demystified/ba-p/3716838)

**Comment by allxiao** [comment]
As previously mentioned, operations on AKS are done in two phases: 1) provision and node pool manipulation through ARM, publicly, 2) operation on Kubernetes resources through the API server, either publicly or via private network.

The private endpoint for AKS is done on the 2) part, on the API server. All ARM operations are done through public network.

However, in ASA we don't have such kind of API server concept. All resource operations are done through ARM endpoints, publicly. We cannot inject ARM frontend to the user's private network.
