### ISSUE TITLE
How can we add server credentials for maven repo?

### ISSUE THREAD

**Issue by helayoty** [Azure/Azure-Spring-Apps#3]
**Describe the bug**

We have a maven artifacts repo in ADO (not in Github). We need a way to set the username/password to be able to access this repo.

Currently in settings.xml

`<server>
          <id></id>
          <username></username>
          <password></password>
     </server>`

How can we do the same using the config server? Is there another way to do so?

**To Reproduce**

1. trying to follow the instructions to use maven as stated [here](https://docs.microsoft.com/en-us/azure/spring-cloud/spring-cloud-quickstart-launch-app-maven)

2. can't find a way to define the artifact repo from ADO

**Expected behavior**

Be able to add a private repo creditial 

**Screenshots**
NA

**Additional context**
NA

**Comment by xscript** [comment]
@helayoty  My understanding is you are trying to point Config Server to a private Git repository in ADO,
Have you checked out below links?
https://docs.microsoft.com/en-us/azure/spring-cloud/spring-cloud-tutorial-config-server#private-repository
https://docs.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops

**Comment by allxiao** [comment]
Close this as no response for a long time.
