### ISSUE TITLE
Availabliity of UK-West region for Azure Spring Apps

### ISSUE THREAD

**Issue by SravanBitla** [Azure/Azure-Spring-Apps#34]
**Is your feature request related to a problem? Please describe.**
Yes for Disaster Recovery UK-West region avaialability is a must

All the resource components exists in UK-west for our custom application except Azure Spring Apps
**Describe the solution you'd like**

we cannot keep in Europe west due to compliance and GDPR sensitivity purposes.
**Describe alternatives you've considered**

**Describe the Customer Impact**
customer is in gas industry and is very important to get this HA in UK-West region.

A clear description about the Impact to the customer.

**Additional context**
customer can wait for 6months-1year but needs committment timeframe to get this deployed.

**Can we contact you for additional details?** Y/N
yes please
If yes, please send us your contact information to AzureSpringCloud-Talk@service.microsoft.com and include the issue number in the email title.
Please contact me over below details
sravan.bitla@wipro.com

**Comment by seanli1988** [comment]
We are working on UK west availability. ETA is May 14 2023.

**Comment by SravanBitla** [comment]
Thank you for your email. We look forward to hearing from you about the
progress on this.

Regards,
Sravan

**Comment by allxiao** [comment]
Hi @SravanBitla , the UK West is now available for Azure Spring Apps Basic / Standard and Enterprise tier. You can try it now.

**Comment by SravanBitla** [comment]
Thank you for informing.
