### ISSUE TITLE
App To App communication : TLS enforcment

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/Azure-Spring-Apps#39]
**Is your feature request related to a problem? Please describe.**

[https://learn.microsoft.com/en-us/azure/spring-apps/secure-communications-end-to-end#segment-4-secure-app-to-app-communications](https://learn.microsoft.com/en-us/azure/spring-apps/secure-communications-end-to-end#segment-4-secure-app-to-app-communications) shows how to enable TlS from Spring Cloud Gateway to 1 App but how to enforce TLS from App1 say to App2 ?

**Describe the solution you'd like**

**Describe alternatives you've considered**

[Service-Mesh in AKS or Dapr with ACA](https://docs.dapr.io/concepts/service-mesh)

**Describe the Customer Impact**

**Additional context**

**Can we contact you for additional details?** Y/N

If yes, please send us your contact information to AzureSpringCloud-Talk@service.microsoft.com and include the issue number in the email title.

**Comment by zmssp** [comment]
TLS between App1 and App2 is the same as gateway to app1. It is enabled by customers.
