### ISSUE TITLE
Error while Launch an Azure Spring Cloud app by using the Maven plug-in

### ISSUE THREAD

**Issue by helayoty** [Azure/Azure-Spring-Apps#4]
**Describe the bug**

**To Reproduce**

Pre-steps: I followed the steps [here](https://docs.microsoft.com/en-us/azure/spring-cloud/spring-cloud-quickstart-launch-app-cli) to login into az and configure my spring-cloud service

1. Clone the code from ADO
2. Add all maven dependencies as stated [here](https://docs.microsoft.com/en-us/azure/spring-cloud/spring-cloud-tutorial-prepare-app-deployment) 
3. install the cli extension `az extension add -y --source https://azureclitemp.blob.core.windows.net/spring-cloud/spring_cloud-0.1.0-py2.py3-none-any.whl
` 
4. Perform `mvn clean package -DskipTests`
5. Perform `mvn com.microsoft.azure:azure-spring-cloud-maven-plugin:0.1.0-SNAPSHOT:config` and follow steps by entering the app name and expose public access.
6. Perform `mvn com.microsoft.azure:azure-spring-cloud-maven-plugin:0.1.0-SNAPSHOT:deploy`

The result:

1. I got the following error:

`[ERROR] Failed to execute goal com.microsoft.azure:azure-spring-cloud-maven-plugin:0.1.0-SNAPSHOT:deploy (default-cli) on project<my_project_name>: Target file does not exist or is not executable, please check the configuration. ->`

2. when I checked the portal, I found my app has been created with status disabled as well as the deployment has been created without any version. Please refer to screenshots

**Expected behavior**

1. app should be deployed successfully
2. if something happened, everything should be rollback.

**Screenshots**

![image](https://user-images.githubusercontent.com/31887807/67604993-ed683b00-f731-11e9-8707-a6ad0442393d.png)

![image](https://user-images.githubusercontent.com/31887807/67604954-d0336c80-f731-11e9-865a-0db818f804ce.png)

**Additional context**

**Comment by allxiao** [comment]
It seems this issue was not tracked properly in the early days.

For the "Target file does not exist or is not executable, please check the configuration." please check if the JAR file is properly generated in the `target` folder, and confirm the `/deployment/resources` configuration for the `azure-spring-apps-maven-plugin` is properly configured:

```xml
<configuration>
	...
	<deployment>
		...
		<resources>
			<resource>
				<filtering/>
				<mergeId/>
				<targetPath/>
				<directory>${project.basedir}/target</directory>
				<includes>
					<include>*.jar</include>
				</includes>
			</resource>
		</resources>
	</deployment>
</configuration>
```
