### ISSUE TITLE
Broken Link on Deployments page

### ISSUE THREAD

**Issue by sampeinado** [Azure/Azure-Spring-Apps#5]
**Summary**
Developer should be able to access docs that explain how to create staging deployment.

**Currently:**
When clicking on a link that is supposed to describe how to create a staging deployment, the link to “this document” takes you to the home page for the Azure portal. 

**Expected:**
When clicking on a link that is supposed to describe how to create a staging deployment, the link to “this document” should take you to the Microsoft docs. This is the [page](https://docs.microsoft.com/en-us/azure/spring-cloud/spring-cloud-howto-staging-environment#create-a-staging-deployment) it should link to. 

**STEPS TO REPRODUCE:**
Open the Deployments page.
Click on the link in the blue info box above the page’s main interface. 

**REFERENCE:**
<img width="1280" alt="Screenshot 2019-10-28 at 10 33 50 AM" src="https://user-images.githubusercontent.com/35495560/67687515-cb0f3100-f96e-11e9-9fcd-02bd08aa6473.png">

**Comment by xscript** [comment]
@Sneezry

**Comment by allxiao** [comment]
The portal page had been redesigned and this problem was gone.
