### ISSUE TITLE
Config server does not support RSA key with SHA-2 algorythm

### ISSUE THREAD

**Issue by julienbourgoin-maif** [Azure/Azure-Spring-Apps#53]
**Is your feature request related to a problem? Please describe.**

- We are using github enterprise.
- We would like to use a git repository for the config server with SSH authentication (see https://learn.microsoft.com/en-us/azure/spring-apps/how-to-config-server#private-repository-with-ssh-authentication).
- As we don't wan't to create a "service user" or use a "regular user" on the github side, we wan't to use the "deploy key" feature proposed by github. (https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys)
- We are generating a fresh new ssh key with the following command : `ssh-keygen -m PEM -t rsa -b 4096 -C "email@email.com" -f config-server-ssh-key`
- We are adding the public key on the github side and we configure the config server with the private key on the azure spring app. The validation succeed and then we save this configuration.
- Once the config server is updated, it will fail with the following error :
```
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: git@github.local:config/config-repo.git: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

- the documentation from Azure Spring Apps says that config server only supports RSA SHA-1 keys: 
```
Config Server uses RSA keys with SHA-1 signatures for now. If you're using GitHub, for RSA public keys added to GitHub before November 2, 2021, the corresponding private key is supported. For RSA public keys added to GitHub after November 2, 2021, the corresponding private key is not supported, and we suggest using basic authentication instead.
```

The conclusion of that is that we can't use SSH authentication using deploy keys with github.com or github enterprise until config server supports RSA SHA-2.

**Describe alternatives you've considered**

An alternative would be to use basic authentication, as advised by the Azure Spring Apps documentation, but this requires a valid user on the github side and we wanted to avoid that.

So the question is : will config server support RSA SHA-2 in a near future ?

**Comment by leonard520** [comment]
@julienbourgoin-maif Thanks for reaching out.
Config Server start to support SHA-2 signature from 3.1.4. However, there are several critical bugs that contains regression issue in that version (https://github.com/spring-cloud/spring-cloud-config/issues/2158) and even in the latter version 3.1.5 (https://github.com/spring-cloud/spring-cloud-config/issues/2201). We hold on the upgrade to the latest version and keeps evaluating 3.1.6. The upgrade is put into the plan now and will be support in near feature.

**Comment by jiec-msft** [comment]
Hey @julienbourgoin-maif,

We've upgrade Config Server in Azure Spring Apps (ASA) basic/standard tiers to support RSA key with SHA-2 algorithm. For existed ASA instance, you might need to update the Config Server through control plane to take effect. For new provisioned ASA instance, it should be already supported.

Feel free to comment for anything, thank you!

Meanwhile, I'll close this issue. Feel free to re-open if there is still an issue.
