### ISSUE TITLE
No warning to users whose staging deployment does not match their production deployment when they set a new deployment

### ISSUE THREAD

**Issue by sampeinado** [Azure/Azure-Spring-Apps#7]
**Is your feature request related to a problem? Please describe.**

As an app developer, when I set a new deployment with a different scale than the existing deployment, there is no warning that tells me that I am about to reduce the number of instances or vCPU/memory which will be in production. 

When this feature was shown to a Spring expert with PaaS experience, he expressed frustration that the system is not making sensible default scaling choices for the user when switching deployments.

**Describe the solution you'd like**

When I set a new deployment with different scale than the existing deployment, I want to see a warning that my deployments are not at the same scale, and I may want to scale my staging deployment first before setting it as the production deployment. 

"*Warning:* Your two deployments are not equally scaled. You may want to scale your staging deployment before setting it as the production deployment"

**Describe alternatives you've considered**

Another way to remedy this issue would be to automatically scale up the staging deployment before initiating the deployment switch. It would be reasonable to assume that the user wants their new production deployment to operate at the same level of scale as their existing production deployment. However, this would probably require more work than simply printing a warning, so I recommend simply printing a warning to the user as a first step. 

**Additional context**
<img width="1680" alt="Screen Shot 2019-11-15 at 11 21 38 AM" src="https://user-images.githubusercontent.com/35495560/68966301-ff6e5400-079a-11ea-93e0-f363a6639253.png">

**Comment by allxiao** [comment]
@zmssp is this still valid?

**Comment by yuwzho** [comment]
This is the current design which can tell the desired instance count used by theh deployment

![image](https://user-images.githubusercontent.com/14213176/226248711-b9ba89a1-6484-4a7b-8411-80d05c6645c3.png)
